deployments:
  giropops-senhas:
    name: "giropops-senhas-helm"
    image: "linuxtips/giropops-senhas:1.0" 
    labels:
      app: "giropops-senhas"
      env: "labs"
      live: "true"
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    env:
    - name: REDIS_HOST
      value: redis-svc
  redis:
    name: "redis-helm"
    image: "redis"
    replicas: "1"
    labels:
      app: "redis"
      env: "labs"
      live: "true"
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"

services:
  giropops-senhas:
    ports:
    - port: 5000
      targetPort: 5000
      name: "app"
      type: "ClusterIP"
      NodePort: 32500
    - port: 8088
      targetPort: 8088
      name: "metrics"
      type: "ClusterIP"
    labels:
      app: "giropops-senhas"
      env: "labs"
      live: "true"
  redis:
    ports:
    - port: 6379
      targetPort: 6379
      name: "svc"
      type: "ClusterIP"
    labels:
      app: "redis"
      env: "labs"
      live: "true"

observability:
  giropops-senhas:
    logging: true
    metrics: 
      enabled: true
      path: "/metrics"

databases:
  giropops-senhas:
    mysql:
      host: "mysql.svc.cluster.local"
      port: 3306
      name: "MyDB"
